### ISSUE TITLE
Feedback zum Testat

### ISSUE THREAD

**Issue by thomsmits** [tpe-lecture/repo-38#1]
Bitte korrigieren Sie die folgenden Fehler und checken Sie dann die korrigierte Version ein. Danach können Sie dieses Issue schließen.

  * JavaDoc ergänzen, diese fehlt vollständig
  * Ihre Implementierung geht nicht richtig mit Eingaben zu `encrypt()` um, die ungültige Zeichen enthalten. Diese sollen stillschweigend entfernt werden.
  * `encrpyt()` und `decrypt()` enthalten doppelten Code, bitte diesen entfernen.

**Comment by thomsmits** [comment]
Klasse hat immer noch keine JavaDoc. Bitte ergänzen Sie diese.

**Comment by Murmelmunz** [comment]
Fehler müsste behoben sein.
